### ISSUE TITLE
GDAL version

### ISSUE THREAD

**Issue by FionaEileen** [marinetraffic/mt-ais-toolbox#9]
Regarding the toolbox requirements, does the GDAL version specifically need to be version 3.0.4? I have version 3.4.3 installed using a .whl file however I am having issues, could it be down to this?

**Comment by giannismt** [comment]
Hi Fiona, 

We do not  explicitly require version 3.0.4  I have confirmed that is works up to 3.4.1 that I have installed in my system.

I believe this issue is related with shapely 2.0.0 that we were not able to adapt yet as mentioned in [Issue#8](https://github.com/marinetraffic/mt-ais-toolbox/issues/8).
